In [1]:
#!/usr/bin/env python
# coding: utf-8

# Library Import
import pandas as pd

# Importing Dataset
file_path = r"../data/T_ONTIME_REPORTING.csv"
df = pd.read_csv(file_path)

# Display df
df.head(10)

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,CRS_ARR_TIME,ARR_TIME,ARR_DELAY
0,2025,1,1,3,10135,1013506,30135,ABE,11057,1105703,31057,CLT,606,556.0,-10.0,812,736.0,-36.0
1,2025,1,1,3,10135,1013506,30135,ABE,11057,1105703,31057,CLT,1219,1215.0,-4.0,1417,1405.0,-12.0
2,2025,1,1,3,10135,1013506,30135,ABE,11057,1105703,31057,CLT,1738,1730.0,-8.0,1934,1920.0,-14.0
3,2025,1,1,3,10135,1013506,30135,ABE,14082,1408203,34082,PGD,830,820.0,-10.0,1130,1127.0,-3.0
4,2025,1,1,3,10135,1013506,30135,ABE,14112,1411206,33195,PIE,1551,1547.0,-4.0,1850,1837.0,-13.0
5,2025,1,1,3,10135,1013506,30135,ABE,14761,1476107,34761,SFB,1100,1051.0,-9.0,1338,1318.0,-20.0
6,2025,1,1,3,10136,1013603,30136,ABI,11298,1129806,30194,DFW,627,622.0,-5.0,728,709.0,-19.0
7,2025,1,1,3,10136,1013603,30136,ABI,11298,1129806,30194,DFW,800,755.0,-5.0,901,854.0,-7.0
8,2025,1,1,3,10136,1013603,30136,ABI,11298,1129806,30194,DFW,1035,1029.0,-6.0,1136,1127.0,-9.0
9,2025,1,1,3,10136,1013603,30136,ABI,11298,1129806,30194,DFW,1446,1438.0,-8.0,1543,1524.0,-19.0

In [2]:
# Column Formatting & Filtering

# | YEAR | MONTH | DAY | DAY_OF_WEEK | ORG_AIRPORT | DEST_AIRPORT | SCHEDULED_DEPARTURE | DEPARTURE_TIME | DEPARTURE_DELAY | SCHEDULED_ARRIVAL | ARRIVAL_TIME | ARRIVAL_DELAY |
# |:--------:|:--------:|:--------:|:--------:|:--------:|:--------:|:--------:|:--------:|:--------:|:--------:|:--------:|:--------:|
# | integer | integer | integer | integer | string | string | integer | integer | integer | integer | integer | integer |


# Select only the required columns and rename them
df = df.rename(columns={
    'DAY_OF_MONTH': 'DAY',
    'ORIGIN': 'ORG_AIRPORT',
    'DEST': 'DEST_AIRPORT',
    'CRS_DEP_TIME': 'SCHEDULED_DEPARTURE',
    'DEP_TIME': 'DEPARTURE_TIME',
    'DEP_DELAY': 'DEPARTURE_DELAY',
    'CRS_ARR_TIME': 'SCHEDULED_ARRIVAL',
    'ARR_TIME': 'ARRIVAL_TIME',
    'ARR_DELAY': 'ARRIVAL_DELAY'
})[['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'ORG_AIRPORT', 'DEST_AIRPORT', 
     'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'DEPARTURE_DELAY', 
     'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME', 'ARRIVAL_DELAY']]


# Convert all columns except ORG_AIRPORT and DEST_AIRPORT to integer type
# df = df.apply(lambda col: col.astype('Int64') if col.name not in ['ORG_AIRPORT', 'DEST_AIRPORT'] else col)

# Check data types of each column
print(df.dtypes)

display(df)

YEAR                     int64
MONTH                    int64
DAY                      int64
DAY_OF_WEEK              int64
ORG_AIRPORT             object
DEST_AIRPORT            object
SCHEDULED_DEPARTURE      int64
DEPARTURE_TIME         float64
DEPARTURE_DELAY        float64
SCHEDULED_ARRIVAL        int64
ARRIVAL_TIME           float64
ARRIVAL_DELAY          float64
dtype: object

,YEAR,MONTH,DAY,DAY_OF_WEEK,ORG_AIRPORT,DEST_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY
0,2025,1,1,3,ABE,CLT,606,556.0,-10.0,812,736.0,-36.0
1,2025,1,1,3,ABE,CLT,1219,1215.0,-4.0,1417,1405.0,-12.0
2,2025,1,1,3,ABE,CLT,1738,1730.0,-8.0,1934,1920.0,-14.0
3,2025,1,1,3,ABE,PGD,830,820.0,-10.0,1130,1127.0,-3.0
4,2025,1,1,3,ABE,PIE,1551,1547.0,-4.0,1850,1837.0,-13.0
...,...,...,...,...,...,...,...,...,...,...,...,...
539742,2025,1,31,5,XWA,DEN,1345,1514.0,89.0,1500,1638.0,98.0
539743,2025,1,31,5,XWA,DEN,1515,1711.0,116.0,1630,1849.0,139.0
539744,2025,1,31,5,XWA,DEN,1705,1725.0,20.0,1820,1908.0,48.0
539745,2025,1,31,5,XWA,MSP,715,706.0,-9.0,927,917.0,-10.0
539746,2025,1,31,5,XWA,MSP,1240,1234.0,-6.0,1445,1426.0,-19.0

In [3]:
# Filtering by Origin Airport (ATL)
# Dest Airport ID: 10397

df_atl = df[df['ORG_AIRPORT'] == 'ATL']

# Display the filtered dataframe
print(df_atl)

df = df_atl

        YEAR  MONTH  DAY  DAY_OF_WEEK ORG_AIRPORT DEST_AIRPORT  \
195     2025      1    1            3         ATL          ABQ
196     2025      1    1            3         ATL          ABQ
197     2025      1    1            3         ATL          ALB
198     2025      1    1            3         ATL          ALB
199     2025      1    1            3         ATL          ASE
...      ...    ...  ...          ...         ...          ...
522724  2025      1   31            5         ATL          VPS
522725  2025      1   31            5         ATL          VPS
522726  2025      1   31            5         ATL          VPS
522727  2025      1   31            5         ATL          VPS
522728  2025      1   31            5         ATL          VPS

        SCHEDULED_DEPARTURE  DEPARTURE_TIME  DEPARTURE_DELAY  \
195                     900           903.0              3.0
196                    1925          1922.0             -3.0
197                    1102          1104.0              2.0
198                    1926          1920.0             -6.0
199                    1000           958.0             -2.0
...                     ...             ...              ...
522724                 1100          1057.0             -3.0
522725                 1359          1355.0             -4.0
522726                 1545          1626.0             41.0
522727                 1807          1802.0             -5.0
522728                 2242          2240.0             -2.0

        SCHEDULED_ARRIVAL  ARRIVAL_TIME  ARRIVAL_DELAY
195                  1029        1039.0           10.0
196                  2052        2059.0            7.0
197                  1318        1315.0           -3.0
198                  2139        2130.0           -9.0
199                  1157        1235.0           38.0
...                   ...           ...            ...
522724               1114        1108.0           -6.0
522725               1410        1410.0            0.0
522726               1557        1648.0           51.0
522727               1820        1817.0           -3.0
522728               2253        2247.0           -6.0

[23881 rows x 12 columns]

In [4]:
# Check for missing values by column
missing_values = df.isnull().sum()

print(missing_values)

YEAR                      0
MONTH                     0
DAY                       0
DAY_OF_WEEK               0
ORG_AIRPORT               0
DEST_AIRPORT              0
SCHEDULED_DEPARTURE       0
DEPARTURE_TIME         1179
DEPARTURE_DELAY        1187
SCHEDULED_ARRIVAL         0
ARRIVAL_TIME           1261
ARRIVAL_DELAY          1301
dtype: int64

In [5]:
# Dropping rows with missing values in specific columns
df.dropna(subset=['DEPARTURE_TIME', 'DEPARTURE_DELAY', 'ARRIVAL_TIME', 'ARRIVAL_DELAY'], inplace=True)

#Ensuring null data is removed
missing_values = df.isnull().sum()

display(missing_values)

YEAR                   0
MONTH                  0
DAY                    0
DAY_OF_WEEK            0
ORG_AIRPORT            0
DEST_AIRPORT           0
SCHEDULED_DEPARTURE    0
DEPARTURE_TIME         0
DEPARTURE_DELAY        0
SCHEDULED_ARRIVAL      0
ARRIVAL_TIME           0
ARRIVAL_DELAY          0
dtype: int64

In [6]:
# Convert ORG_AIRPORT and DEST_AIRPORT to string type
# MLFlow has issues with integer types for these columns - deprecated typing"
df[['ORG_AIRPORT', 'DEST_AIRPORT']] = df[['ORG_AIRPORT', 'DEST_AIRPORT']].astype(str)

# Verify the changes
print(df.dtypes)

YEAR                     int64
MONTH                    int64
DAY                      int64
DAY_OF_WEEK              int64
ORG_AIRPORT             object
DEST_AIRPORT            object
SCHEDULED_DEPARTURE      int64
DEPARTURE_TIME         float64
DEPARTURE_DELAY        float64
SCHEDULED_ARRIVAL        int64
ARRIVAL_TIME           float64
ARRIVAL_DELAY          float64
dtype: object

In [7]:
# Identify duplicate rows
duplicates = df.duplicated()

# Count the number of duplicate rows
num_duplicates = duplicates.sum()
print(f"Number of duplicate rows: {num_duplicates}")

# Display duplicate rows if any
if num_duplicates > 0:
    # Display the duplicate rows before dropping them
    display(df[duplicates])
    
    # Drop duplicate rows
    df.drop_duplicates(inplace=True)
    
    # Recalculate the number of duplicate rows
    new_num_duplicates = df.duplicated().sum()
    
    # Print the number of duplicates removed
    print(f"Number of duplicate rows removed: {num_duplicates - new_num_duplicates}")

Number of duplicate rows: 0

In [8]:
# Dropping spaces before and after each cell
df = df.apply(lambda col: col.map(lambda x: x.strip() if isinstance(x, str) else x))

In [9]:
# Save the dataframe to a CSV file
df.to_csv('cleaned_data.csv', index=False)